apiVersion: v2
name: olivetin
description: A OliveTin Helm chart for Kubernetes
icon: https://www.olivetin.app/resources/images/logo.png
home: https://www.olivetin.app
sources:
  - https://github.com/OliveTin/OliveTin
maintainers:
  - name: OliveTin contributors
    url: https://github.com/OliveTin/OliveTin

type: application

version: 2.2.0

appVersion: "2025.4.8"

keywords:
  - olivetin
  - shell
  - commands
